/**
 * Auto-generated Facet types for feature: generate
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "generate" feature
 */
export type FacetId =
  | 'features/cli/generate/product:generate-command'
  | 'features/cli/generate/product:config-based-discovery'
  | 'features/cli/generate/product:config-based-discovery/read-config'
  | 'features/cli/generate/product:config-based-discovery/glob-array'
  | 'features/cli/generate/product:config-based-discovery/recursive-discovery'
  | 'features/cli/generate/product:config-based-discovery/group-by-feature'
  | 'features/cli/generate/product:type-generation'
  | 'features/cli/generate/product:type-generation/facet-id-union'
  | 'features/cli/generate/product:type-generation/facets-const-object'
  | 'features/cli/generate/product:type-generation/facet-helper'
  | 'features/cli/generate/product:type-generation/no-types-flag'
  | 'features/cli/generate/product:global-types'
  | 'features/cli/generate/product:global-types/root-facets-file'
  | 'features/cli/generate/product:global-types/re-export-types'
  | 'features/cli/generate/product:global-types/combined-union'
  | 'features/cli/generate/product:global-types/combined-const';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Generate Command */
  FEATURES_CLI_GENERATE_PRODUCT_GENERATE_COMMAND: 'features/cli/generate/product:generate-command' as const,
 /** Config-Based Discovery */
  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY: 'features/cli/generate/product:config-based-discovery' as const,

  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY__READ_CONFIG: 'features/cli/generate/product:config-based-discovery/read-config' as const,

  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY__GLOB_ARRAY: 'features/cli/generate/product:config-based-discovery/glob-array' as const,

  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY__RECURSIVE_DISCOVERY: 'features/cli/generate/product:config-based-discovery/recursive-discovery' as const,

  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY__GROUP_BY_FEATURE: 'features/cli/generate/product:config-based-discovery/group-by-feature' as const,
 /** Type Generation */
  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION: 'features/cli/generate/product:type-generation' as const,

  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION__FACET_ID_UNION: 'features/cli/generate/product:type-generation/facet-id-union' as const,

  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION__FACETS_CONST_OBJECT: 'features/cli/generate/product:type-generation/facets-const-object' as const,

  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION__FACET_HELPER: 'features/cli/generate/product:type-generation/facet-helper' as const,

  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION__NO_TYPES_FLAG: 'features/cli/generate/product:type-generation/no-types-flag' as const,
 /** Global Types */
  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES: 'features/cli/generate/product:global-types' as const,

  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES__ROOT_FACETS_FILE: 'features/cli/generate/product:global-types/root-facets-file' as const,

  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES__RE_EXPORT_TYPES: 'features/cli/generate/product:global-types/re-export-types' as const,

  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES__COMBINED_UNION: 'features/cli/generate/product:global-types/combined-union' as const,

  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES__COMBINED_CONST: 'features/cli/generate/product:global-types/combined-const' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework including Playwright
 *
 * @example
 * // Use with Playwright test annotations
 * test('my test', {
 *   annotation: facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW)
 * }, async ({ page }) => { ... });
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): {
  type: 'facet-coverage';
  description: string;
  facets: T[];
  toString: () => string;
} {
  return {
    type: 'facet-coverage',
    description: facetIds.join(','),
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/cli/generate/product:generate-command',
  'features/cli/generate/product:config-based-discovery',
  'features/cli/generate/product:config-based-discovery/read-config',
  'features/cli/generate/product:config-based-discovery/glob-array',
  'features/cli/generate/product:config-based-discovery/recursive-discovery',
  'features/cli/generate/product:config-based-discovery/group-by-feature',
  'features/cli/generate/product:type-generation',
  'features/cli/generate/product:type-generation/facet-id-union',
  'features/cli/generate/product:type-generation/facets-const-object',
  'features/cli/generate/product:type-generation/facet-helper',
  'features/cli/generate/product:type-generation/no-types-flag',
  'features/cli/generate/product:global-types',
  'features/cli/generate/product:global-types/root-facets-file',
  'features/cli/generate/product:global-types/re-export-types',
  'features/cli/generate/product:global-types/combined-union',
  'features/cli/generate/product:global-types/combined-const',
];
