/**
 * Auto-generated Facet types for feature: generate
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "generate" feature
 */
export type FacetId =
  | 'features/cli/generate/product:generate-command'
  | 'features/cli/generate/product:config-based-discovery'
  | 'features/cli/generate/product:type-generation'
  | 'features/cli/generate/product:global-types';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Generate Command */
  FEATURES_CLI_GENERATE_PRODUCT_GENERATE_COMMAND: 'features/cli/generate/product:generate-command' as const,
 /** Config-Based Discovery */
  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY: 'features/cli/generate/product:config-based-discovery' as const,
 /** Type Generation */
  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION: 'features/cli/generate/product:type-generation' as const,
 /** Global Types */
  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES: 'features/cli/generate/product:global-types' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/cli/generate/product:generate-command',
  'features/cli/generate/product:config-based-discovery',
  'features/cli/generate/product:type-generation',
  'features/cli/generate/product:global-types',
];
