/**
 * Auto-generated Facet types for feature: server
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "server" feature
 */
export type FacetId =
  | 'features/server/technical:technical-requirements'
  | 'features/server/technical:http'
  | 'features/server/technical:http/static'
  | 'features/server/technical:http/api'
  | 'features/server/technical:http/spa'
  | 'features/server/technical:websocket'
  | 'features/server/technical:websocket/connect'
  | 'features/server/technical:websocket/broadcast'
  | 'features/server/technical:websocket/disconnect'
  | 'features/server/technical:file-watch'
  | 'features/server/technical:file-watch/glob'
  | 'features/server/technical:file-watch/ignore'
  | 'features/server/technical:file-watch/regenerate'
  | 'features/server/dx:developer-experience'
  | 'features/server/dx:cli'
  | 'features/server/dx:cli/command'
  | 'features/server/dx:cli/port'
  | 'features/server/dx:cli/open'
  | 'features/server/dx:errors'
  | 'features/server/dx:errors/missing'
  | 'features/server/dx:errors/websocket-errors'
  | 'features/server/dx:errors/build'
  | 'features/server/product:server-features'
  | 'features/server/product:dashboard'
  | 'features/server/product:dashboard/counts'
  | 'features/server/product:dashboard/by-type'
  | 'features/server/product:dashboard/features'
  | 'features/server/product:dashboard/uncovered'
  | 'features/server/product:hot-reload'
  | 'features/server/product:hot-reload/facets'
  | 'features/server/product:hot-reload/tests'
  | 'features/server/product:hot-reload/websocket'
  | 'features/server/product:hot-reload/debounce'
  | 'features/server/product:doc-viewer'
  | 'features/server/product:doc-viewer/markdown'
  | 'features/server/product:doc-viewer/badges'
  | 'features/server/product:doc-viewer/linked-tests'
  | 'features/server/product:doc-viewer/source';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Technical Requirements */
  FEATURES_SERVER_TECHNICAL_TECHNICAL_REQUIREMENTS: 'features/server/technical:technical-requirements' as const,
 /** HTTP Server */
  FEATURES_SERVER_TECHNICAL_HTTP: 'features/server/technical:http' as const,

  FEATURES_SERVER_TECHNICAL_HTTP__STATIC: 'features/server/technical:http/static' as const,

  FEATURES_SERVER_TECHNICAL_HTTP__API: 'features/server/technical:http/api' as const,

  FEATURES_SERVER_TECHNICAL_HTTP__SPA: 'features/server/technical:http/spa' as const,
 /** WebSocket Server */
  FEATURES_SERVER_TECHNICAL_WEBSOCKET: 'features/server/technical:websocket' as const,

  FEATURES_SERVER_TECHNICAL_WEBSOCKET__CONNECT: 'features/server/technical:websocket/connect' as const,

  FEATURES_SERVER_TECHNICAL_WEBSOCKET__BROADCAST: 'features/server/technical:websocket/broadcast' as const,

  FEATURES_SERVER_TECHNICAL_WEBSOCKET__DISCONNECT: 'features/server/technical:websocket/disconnect' as const,
 /** File Watching */
  FEATURES_SERVER_TECHNICAL_FILE_WATCH: 'features/server/technical:file-watch' as const,

  FEATURES_SERVER_TECHNICAL_FILE_WATCH__GLOB: 'features/server/technical:file-watch/glob' as const,

  FEATURES_SERVER_TECHNICAL_FILE_WATCH__IGNORE: 'features/server/technical:file-watch/ignore' as const,

  FEATURES_SERVER_TECHNICAL_FILE_WATCH__REGENERATE: 'features/server/technical:file-watch/regenerate' as const,
 /** Developer Experience */
  FEATURES_SERVER_DX_DEVELOPER_EXPERIENCE: 'features/server/dx:developer-experience' as const,
 /** CLI Integration */
  FEATURES_SERVER_DX_CLI: 'features/server/dx:cli' as const,

  FEATURES_SERVER_DX_CLI__COMMAND: 'features/server/dx:cli/command' as const,

  FEATURES_SERVER_DX_CLI__PORT: 'features/server/dx:cli/port' as const,

  FEATURES_SERVER_DX_CLI__OPEN: 'features/server/dx:cli/open' as const,
 /** Error Handling */
  FEATURES_SERVER_DX_ERRORS: 'features/server/dx:errors' as const,

  FEATURES_SERVER_DX_ERRORS__MISSING: 'features/server/dx:errors/missing' as const,

  FEATURES_SERVER_DX_ERRORS__WEBSOCKET_ERRORS: 'features/server/dx:errors/websocket-errors' as const,

  FEATURES_SERVER_DX_ERRORS__BUILD: 'features/server/dx:errors/build' as const,
 /** Server Features */
  FEATURES_SERVER_PRODUCT_SERVER_FEATURES: 'features/server/product:server-features' as const,
 /** Live Coverage Dashboard */
  FEATURES_SERVER_PRODUCT_DASHBOARD: 'features/server/product:dashboard' as const,

  FEATURES_SERVER_PRODUCT_DASHBOARD__COUNTS: 'features/server/product:dashboard/counts' as const,

  FEATURES_SERVER_PRODUCT_DASHBOARD__BY_TYPE: 'features/server/product:dashboard/by-type' as const,

  FEATURES_SERVER_PRODUCT_DASHBOARD__FEATURES: 'features/server/product:dashboard/features' as const,

  FEATURES_SERVER_PRODUCT_DASHBOARD__UNCOVERED: 'features/server/product:dashboard/uncovered' as const,
 /** Hot Reload */
  FEATURES_SERVER_PRODUCT_HOT_RELOAD: 'features/server/product:hot-reload' as const,

  FEATURES_SERVER_PRODUCT_HOT_RELOAD__FACETS: 'features/server/product:hot-reload/facets' as const,

  FEATURES_SERVER_PRODUCT_HOT_RELOAD__TESTS: 'features/server/product:hot-reload/tests' as const,

  FEATURES_SERVER_PRODUCT_HOT_RELOAD__WEBSOCKET: 'features/server/product:hot-reload/websocket' as const,

  FEATURES_SERVER_PRODUCT_HOT_RELOAD__DEBOUNCE: 'features/server/product:hot-reload/debounce' as const,
 /** Facet Documentation Viewer */
  FEATURES_SERVER_PRODUCT_DOC_VIEWER: 'features/server/product:doc-viewer' as const,

  FEATURES_SERVER_PRODUCT_DOC_VIEWER__MARKDOWN: 'features/server/product:doc-viewer/markdown' as const,

  FEATURES_SERVER_PRODUCT_DOC_VIEWER__BADGES: 'features/server/product:doc-viewer/badges' as const,

  FEATURES_SERVER_PRODUCT_DOC_VIEWER__LINKED_TESTS: 'features/server/product:doc-viewer/linked-tests' as const,

  FEATURES_SERVER_PRODUCT_DOC_VIEWER__SOURCE: 'features/server/product:doc-viewer/source' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/server/technical:technical-requirements',
  'features/server/technical:http',
  'features/server/technical:http/static',
  'features/server/technical:http/api',
  'features/server/technical:http/spa',
  'features/server/technical:websocket',
  'features/server/technical:websocket/connect',
  'features/server/technical:websocket/broadcast',
  'features/server/technical:websocket/disconnect',
  'features/server/technical:file-watch',
  'features/server/technical:file-watch/glob',
  'features/server/technical:file-watch/ignore',
  'features/server/technical:file-watch/regenerate',
  'features/server/dx:developer-experience',
  'features/server/dx:cli',
  'features/server/dx:cli/command',
  'features/server/dx:cli/port',
  'features/server/dx:cli/open',
  'features/server/dx:errors',
  'features/server/dx:errors/missing',
  'features/server/dx:errors/websocket-errors',
  'features/server/dx:errors/build',
  'features/server/product:server-features',
  'features/server/product:dashboard',
  'features/server/product:dashboard/counts',
  'features/server/product:dashboard/by-type',
  'features/server/product:dashboard/features',
  'features/server/product:dashboard/uncovered',
  'features/server/product:hot-reload',
  'features/server/product:hot-reload/facets',
  'features/server/product:hot-reload/tests',
  'features/server/product:hot-reload/websocket',
  'features/server/product:hot-reload/debounce',
  'features/server/product:doc-viewer',
  'features/server/product:doc-viewer/markdown',
  'features/server/product:doc-viewer/badges',
  'features/server/product:doc-viewer/linked-tests',
  'features/server/product:doc-viewer/source',
];
