/**
 * Auto-generated Facet types for feature: cli
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "cli" feature
 */
export type FacetId =
  | 'features/cli/dx:developer-experience'
  | 'features/cli/dx:cli-ergonomics'
  | 'features/cli/dx:configuration-discovery'
  | 'features/cli/product:cli-commands'
  | 'features/cli/product:generate-command'
  | 'features/cli/product:analyze-command'
  | 'features/cli/product:validate-command'
  | 'features/cli/product:watch-command';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Developer Experience */
  FEATURES_CLI_DX_DEVELOPER_EXPERIENCE: 'features/cli/dx:developer-experience' as const,
 /** CLI Ergonomics */
  FEATURES_CLI_DX_CLI_ERGONOMICS: 'features/cli/dx:cli-ergonomics' as const,
 /** Configuration Discovery */
  FEATURES_CLI_DX_CONFIGURATION_DISCOVERY: 'features/cli/dx:configuration-discovery' as const,
 /** CLI Commands */
  FEATURES_CLI_PRODUCT_CLI_COMMANDS: 'features/cli/product:cli-commands' as const,
 /** Generate Command */
  FEATURES_CLI_PRODUCT_GENERATE_COMMAND: 'features/cli/product:generate-command' as const,
 /** Analyze Command */
  FEATURES_CLI_PRODUCT_ANALYZE_COMMAND: 'features/cli/product:analyze-command' as const,
 /** Validate Command */
  FEATURES_CLI_PRODUCT_VALIDATE_COMMAND: 'features/cli/product:validate-command' as const,
 /** Watch Command */
  FEATURES_CLI_PRODUCT_WATCH_COMMAND: 'features/cli/product:watch-command' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/cli/dx:developer-experience',
  'features/cli/dx:cli-ergonomics',
  'features/cli/dx:configuration-discovery',
  'features/cli/product:cli-commands',
  'features/cli/product:generate-command',
  'features/cli/product:analyze-command',
  'features/cli/product:validate-command',
  'features/cli/product:watch-command',
];
