/**
 * Auto-generated Facet types for feature: checkout
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "checkout" feature
 */
export type FacetId =
  | 'business:business-requirements'
  | 'business:guest-purchase-flow'
  | 'business:cart-management'
  | 'compliance:compliance-requirements'
  | 'compliance:pci-dss-payment-requirements'
  | 'compliance:gdpr-data-handling'
  | 'ux:ux-requirements'
  | 'ux:mobile-checkout-experience'
  | 'ux:form-validation';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Business Requirements */
  BUSINESS_BUSINESS_REQUIREMENTS: 'business:business-requirements' as const,
 /** Guest Purchase Flow */
  BUSINESS_GUEST_PURCHASE_FLOW: 'business:guest-purchase-flow' as const,
 /** Cart Management */
  BUSINESS_CART_MANAGEMENT: 'business:cart-management' as const,
 /** Compliance Requirements */
  COMPLIANCE_COMPLIANCE_REQUIREMENTS: 'compliance:compliance-requirements' as const,
 /** PCI-DSS Payment Requirements */
  COMPLIANCE_PCI_DSS_PAYMENT_REQUIREMENTS: 'compliance:pci-dss-payment-requirements' as const,
 /** GDPR Data Handling */
  COMPLIANCE_GDPR_DATA_HANDLING: 'compliance:gdpr-data-handling' as const,
 /** UX Requirements */
  UX_UX_REQUIREMENTS: 'ux:ux-requirements' as const,
 /** Mobile Checkout Experience */
  UX_MOBILE_CHECKOUT_EXPERIENCE: 'ux:mobile-checkout-experience' as const,
 /** Form Validation */
  UX_FORM_VALIDATION: 'ux:form-validation' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'business:business-requirements',
  'business:guest-purchase-flow',
  'business:cart-management',
  'compliance:compliance-requirements',
  'compliance:pci-dss-payment-requirements',
  'compliance:gdpr-data-handling',
  'ux:ux-requirements',
  'ux:mobile-checkout-experience',
  'ux:form-validation',
];
