/**
 * Auto-generated Facet types for feature: checkout
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "checkout" feature
 */
export type FacetId =
  | 'business:business-requirements'
  | 'business:guest-purchase-flow'
  | 'business:cart-management'
  | 'ux:ux-requirements'
  | 'ux:mobile-checkout'
  | 'ux:mobile-checkout/responsive'
  | 'ux:mobile-checkout/responsive/performance'
  | 'ux:mobile-checkout/accessibility'
  | 'ux:form-validation'
  | 'compliance:compliance-requirements'
  | 'compliance:pci-dss'
  | 'compliance:pci-dss/tls'
  | 'compliance:pci-dss/cvv'
  | 'compliance:pci-dss/masking'
  | 'compliance:pci-dss/logging'
  | 'compliance:pci-dss/fraud'
  | 'compliance:gdpr';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Business Requirements */
  BUSINESS_BUSINESS_REQUIREMENTS: 'business:business-requirements' as const,
 /** Guest Purchase Flow */
  BUSINESS_GUEST_PURCHASE_FLOW: 'business:guest-purchase-flow' as const,
 /** Cart Management */
  BUSINESS_CART_MANAGEMENT: 'business:cart-management' as const,
 /** UX Requirements */
  UX_UX_REQUIREMENTS: 'ux:ux-requirements' as const,
 /** Mobile Checkout Experience */
  UX_MOBILE_CHECKOUT: 'ux:mobile-checkout' as const,
 /** Mobile Layout Requirements */
  UX_MOBILE_CHECKOUT__RESPONSIVE: 'ux:mobile-checkout/responsive' as const,

  UX_MOBILE_CHECKOUT__RESPONSIVE__PERFORMANCE: 'ux:mobile-checkout/responsive/performance' as const,
 /** Accessibility */
  UX_MOBILE_CHECKOUT__ACCESSIBILITY: 'ux:mobile-checkout/accessibility' as const,
 /** Form Validation */
  UX_FORM_VALIDATION: 'ux:form-validation' as const,
 /** Compliance Requirements */
  COMPLIANCE_COMPLIANCE_REQUIREMENTS: 'compliance:compliance-requirements' as const,
 /** PCI-DSS Payment Requirements */
  COMPLIANCE_PCI_DSS: 'compliance:pci-dss' as const,
 /** Encryption in transit */
  COMPLIANCE_PCI_DSS__TLS: 'compliance:pci-dss/tls' as const,
 /** No CVV storage */
  COMPLIANCE_PCI_DSS__CVV: 'compliance:pci-dss/cvv' as const,
 /** Card masking */
  COMPLIANCE_PCI_DSS__MASKING: 'compliance:pci-dss/masking' as const,
 /** Transaction logging */
  COMPLIANCE_PCI_DSS__LOGGING: 'compliance:pci-dss/logging' as const,
 /** Fraud monitoring */
  COMPLIANCE_PCI_DSS__FRAUD: 'compliance:pci-dss/fraud' as const,
 /** GDPR Data Handling */
  COMPLIANCE_GDPR: 'compliance:gdpr' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'business:business-requirements',
  'business:guest-purchase-flow',
  'business:cart-management',
  'ux:ux-requirements',
  'ux:mobile-checkout',
  'ux:mobile-checkout/responsive',
  'ux:mobile-checkout/responsive/performance',
  'ux:mobile-checkout/accessibility',
  'ux:form-validation',
  'compliance:compliance-requirements',
  'compliance:pci-dss',
  'compliance:pci-dss/tls',
  'compliance:pci-dss/cvv',
  'compliance:pci-dss/masking',
  'compliance:pci-dss/logging',
  'compliance:pci-dss/fraud',
  'compliance:gdpr',
];
