import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { CoverageReport, FacetConfig, FeatureCoverage, FacetCoverage } from '../types.js';
import { defaultConfig } from '../types.js';

/**
 * Generates HTML coverage reports
 */
export class HtmlReporter {
  private config: FacetConfig;

  constructor(config: Partial<FacetConfig> = {}) {
    this.config = { ...defaultConfig, ...config };
  }

  /**
   * Generate HTML report
   */
  generate(report: CoverageReport): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Facet Coverage Report</title>
  <style>
    ${this.getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>💎 Facet Coverage Report</h1>
      <p class="timestamp">Generated: ${new Date(report.timestamp).toLocaleString()}</p>
    </header>

    ${this.generateSummarySection(report)}
    ${this.generateTypeSection(report)}
    ${this.generateFeaturesSection(report)}
    ${this.generateUncoveredSection(report)}

    <footer>
      <p>Generated by <a href="https://github.com/facet-coverage">facet-coverage</a></p>
    </footer>
  </div>

  <script>
    ${this.getScript()}
  </script>
</body>
</html>`;
  }

  /**
   * Get CSS styles
   */
  private getStyles(): string {
    return `
    :root {
      --color-success: #22c55e;
      --color-warning: #eab308;
      --color-error: #ef4444;
      --color-bg: #0f172a;
      --color-card: #1e293b;
      --color-text: #f1f5f9;
      --color-muted: #94a3b8;
      --color-border: #334155;
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: var(--color-bg);
      color: var(--color-text);
      line-height: 1.6;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2.5rem;
      margin-bottom: 0.5rem;
    }

    .timestamp {
      color: var(--color-muted);
    }

    .card {
      background: var(--color-card);
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      border: 1px solid var(--color-border);
    }

    .card h2 {
      margin-bottom: 1rem;
      font-size: 1.25rem;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 1rem;
    }

    .stat {
      text-align: center;
      padding: 1rem;
      background: var(--color-bg);
      border-radius: 8px;
    }

    .stat-value {
      font-size: 2rem;
      font-weight: bold;
    }

    .stat-label {
      color: var(--color-muted);
      font-size: 0.875rem;
    }

    .coverage-bar {
      height: 8px;
      background: var(--color-border);
      border-radius: 4px;
      overflow: hidden;
      margin-top: 0.5rem;
    }

    .coverage-fill {
      height: 100%;
      transition: width 0.3s ease;
    }

    .coverage-fill.success { background: var(--color-success); }
    .coverage-fill.warning { background: var(--color-warning); }
    .coverage-fill.error { background: var(--color-error); }

    .type-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1rem;
    }

    .type-card {
      padding: 1rem;
      background: var(--color-bg);
      border-radius: 8px;
    }

    .type-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.5rem;
    }

    .type-name {
      font-weight: 600;
      text-transform: capitalize;
    }

    .type-percentage {
      font-weight: bold;
    }

    .feature {
      border: 1px solid var(--color-border);
      border-radius: 8px;
      margin-bottom: 1rem;
      overflow: hidden;
    }

    .feature-header {
      padding: 1rem;
      background: var(--color-bg);
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .feature-header:hover {
      background: var(--color-border);
    }

    .feature-name {
      font-weight: 600;
    }

    .feature-stats {
      display: flex;
      gap: 1rem;
      align-items: center;
    }

    .feature-body {
      padding: 1rem;
      display: none;
    }

    .feature.open .feature-body {
      display: block;
    }

    .facet {
      padding: 0.75rem;
      background: var(--color-bg);
      border-radius: 6px;
      margin-bottom: 0.5rem;
    }

    .facet-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .facet-id {
      font-family: monospace;
      font-weight: 600;
    }

    .facet-type {
      font-size: 0.75rem;
      padding: 0.25rem 0.5rem;
      background: var(--color-card);
      border-radius: 4px;
      text-transform: capitalize;
    }

    .facet-source {
      color: var(--color-muted);
      font-size: 0.875rem;
      margin-top: 0.25rem;
    }

    .facet-tests {
      margin-top: 0.5rem;
      font-size: 0.875rem;
    }

    .facet-tests li {
      margin-left: 1rem;
      color: var(--color-muted);
    }

    .badge {
      display: inline-block;
      padding: 0.125rem 0.5rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 600;
    }

    .badge.success { background: var(--color-success); color: #000; }
    .badge.warning { background: var(--color-warning); color: #000; }
    .badge.error { background: var(--color-error); color: #fff; }

    .uncovered-list {
      list-style: none;
    }

    .uncovered-list li {
      padding: 0.75rem;
      background: var(--color-bg);
      border-radius: 6px;
      margin-bottom: 0.5rem;
      border-left: 3px solid var(--color-error);
    }

    footer {
      text-align: center;
      margin-top: 2rem;
      padding-top: 2rem;
      border-top: 1px solid var(--color-border);
      color: var(--color-muted);
    }

    footer a {
      color: var(--color-text);
    }

    .expand-icon {
      transition: transform 0.2s ease;
    }

    .feature.open .expand-icon {
      transform: rotate(90deg);
    }
    `;
  }

  /**
   * Get JavaScript for interactivity
   */
  private getScript(): string {
    return `
    document.querySelectorAll('.feature-header').forEach(header => {
      header.addEventListener('click', () => {
        header.parentElement.classList.toggle('open');
      });
    });
    `;
  }

  /**
   * Generate summary section HTML
   */
  private generateSummarySection(report: CoverageReport): string {
    const coverageClass = this.getCoverageClass(report.summary.percentage);

    return `
    <section class="card">
      <h2>Overall Coverage</h2>
      <div class="summary-grid">
        <div class="stat">
          <div class="stat-value ${coverageClass}">${report.summary.percentage}%</div>
          <div class="stat-label">Coverage</div>
          <div class="coverage-bar">
            <div class="coverage-fill ${coverageClass}" style="width: ${report.summary.percentage}%"></div>
          </div>
        </div>
        <div class="stat">
          <div class="stat-value">${report.summary.totalFacets}</div>
          <div class="stat-label">Total Facets</div>
        </div>
        <div class="stat">
          <div class="stat-value" style="color: var(--color-success)">${report.summary.coveredFacets}</div>
          <div class="stat-label">Covered</div>
        </div>
        <div class="stat">
          <div class="stat-value" style="color: var(--color-error)">${report.summary.uncoveredFacets}</div>
          <div class="stat-label">Uncovered</div>
        </div>
      </div>
    </section>`;
  }

  /**
   * Generate type breakdown section
   */
  private generateTypeSection(report: CoverageReport): string {
    if (report.byType.length === 0) return '';

    const typeCards = report.byType.map(type => {
      const coverageClass = this.getCoverageClass(type.percentage);
      return `
        <div class="type-card">
          <div class="type-header">
            <span class="type-name">${type.type}</span>
            <span class="type-percentage ${coverageClass}">${type.percentage}%</span>
          </div>
          <div class="coverage-bar">
            <div class="coverage-fill ${coverageClass}" style="width: ${type.percentage}%"></div>
          </div>
          <div style="margin-top: 0.5rem; color: var(--color-muted); font-size: 0.875rem;">
            ${type.covered} / ${type.total} covered
          </div>
        </div>`;
    }).join('');

    return `
    <section class="card">
      <h2>Coverage by Type</h2>
      <div class="type-grid">
        ${typeCards}
      </div>
    </section>`;
  }

  /**
   * Generate features section
   */
  private generateFeaturesSection(report: CoverageReport): string {
    const features = report.features.map(feature => this.generateFeatureHtml(feature)).join('');

    return `
    <section class="card">
      <h2>Features</h2>
      ${features}
    </section>`;
  }

  /**
   * Generate HTML for a single feature
   */
  private generateFeatureHtml(feature: FeatureCoverage): string {
    const coverageClass = this.getCoverageClass(feature.percentage);

    const facetsHtml = feature.facets.map(fc => this.generateFacetHtml(fc)).join('');

    return `
    <div class="feature">
      <div class="feature-header">
        <span class="feature-name">
          <span class="expand-icon">▶</span>
          ${feature.feature}
        </span>
        <div class="feature-stats">
          <span class="badge ${coverageClass}">${feature.percentage}%</span>
          <span style="color: var(--color-muted)">${feature.coveredFacets}/${feature.totalFacets} facets</span>
        </div>
      </div>
      <div class="feature-body">
        ${facetsHtml}
      </div>
    </div>`;
  }

  /**
   * Generate HTML for a single facet
   */
  private generateFacetHtml(fc: FacetCoverage): string {
    const statusIcon = fc.covered ? '✅' : '❌';

    let testsHtml = '';
    if (fc.covered && fc.coveredBy.length > 0) {
      const testItems = fc.coveredBy.map(t => `<li>${t.file}: ${t.title}</li>`).join('');
      testsHtml = `
        <div class="facet-tests">
          <strong>Covered by:</strong>
          <ul>${testItems}</ul>
        </div>`;
    }

    return `
    <div class="facet">
      <div class="facet-header">
        <span class="facet-id">${statusIcon} ${fc.facet.id}</span>
        <span class="facet-type">${fc.facet.type}</span>
      </div>
      <div class="facet-source">
        ${fc.facet.source.file}#${fc.facet.source.section}
      </div>
      ${testsHtml}
    </div>`;
  }

  /**
   * Generate uncovered facets section
   */
  private generateUncoveredSection(report: CoverageReport): string {
    if (report.uncovered.length === 0) return '';

    const items = report.uncovered.map(facet => `
      <li>
        <strong>${facet.id}</strong> (${facet.type})<br>
        <span style="color: var(--color-muted)">${facet.source.file}#${facet.source.section}</span>
      </li>`).join('');

    return `
    <section class="card">
      <h2>❌ Uncovered Facets</h2>
      <ul class="uncovered-list">
        ${items}
      </ul>
    </section>`;
  }

  /**
   * Get CSS class for coverage percentage
   */
  private getCoverageClass(percentage: number): string {
    if (percentage >= 80) return 'success';
    if (percentage >= 50) return 'warning';
    return 'error';
  }

  /**
   * Write HTML report to file
   */
  write(report: CoverageReport, cwd: string = process.cwd()): string {
    const outputDir = join(cwd, this.config.output.dir);
    const outputPath = join(outputDir, 'coverage.html');

    // Ensure output directory exists
    mkdirSync(outputDir, { recursive: true });

    const content = this.generate(report);
    writeFileSync(outputPath, content, 'utf-8');

    return outputPath;
  }
}
