/**
 * Auto-generated Facet types for feature: core
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "core" feature
 */
export type FacetId =
  | 'features/core/technical:technical-requirements'
  | 'features/core/technical:typescript-support'
  | 'features/core/technical:bun-compatibility'
  | 'features/core/technical:glob-pattern-handling'
  | 'features/core/technical:markdown-parsing-accuracy'
  | 'features/core/dx:developer-experience'
  | 'features/core/dx:error-messages'
  | 'features/core/dx:api-design'
  | 'features/core/product:core-functionality'
  | 'features/core/product:structure-reading'
  | 'features/core/product:markdown-parsing'
  | 'features/core/product:test-scanning'
  | 'features/core/product:validation'
  | 'features/core/product:coverage-calculation';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Technical Requirements */
  FEATURES_CORE_TECHNICAL_TECHNICAL_REQUIREMENTS: 'features/core/technical:technical-requirements' as const,
 /** TypeScript Support */
  FEATURES_CORE_TECHNICAL_TYPESCRIPT_SUPPORT: 'features/core/technical:typescript-support' as const,
 /** Bun Compatibility */
  FEATURES_CORE_TECHNICAL_BUN_COMPATIBILITY: 'features/core/technical:bun-compatibility' as const,
 /** Glob Pattern Handling */
  FEATURES_CORE_TECHNICAL_GLOB_PATTERN_HANDLING: 'features/core/technical:glob-pattern-handling' as const,
 /** Markdown Parsing Accuracy */
  FEATURES_CORE_TECHNICAL_MARKDOWN_PARSING_ACCURACY: 'features/core/technical:markdown-parsing-accuracy' as const,
 /** Developer Experience */
  FEATURES_CORE_DX_DEVELOPER_EXPERIENCE: 'features/core/dx:developer-experience' as const,
 /** Error Messages */
  FEATURES_CORE_DX_ERROR_MESSAGES: 'features/core/dx:error-messages' as const,
 /** API Design */
  FEATURES_CORE_DX_API_DESIGN: 'features/core/dx:api-design' as const,
 /** Core Functionality */
  FEATURES_CORE_PRODUCT_CORE_FUNCTIONALITY: 'features/core/product:core-functionality' as const,
 /** Structure Reading */
  FEATURES_CORE_PRODUCT_STRUCTURE_READING: 'features/core/product:structure-reading' as const,
 /** Markdown Parsing */
  FEATURES_CORE_PRODUCT_MARKDOWN_PARSING: 'features/core/product:markdown-parsing' as const,
 /** Test Scanning */
  FEATURES_CORE_PRODUCT_TEST_SCANNING: 'features/core/product:test-scanning' as const,
 /** Validation */
  FEATURES_CORE_PRODUCT_VALIDATION: 'features/core/product:validation' as const,
 /** Coverage Calculation */
  FEATURES_CORE_PRODUCT_COVERAGE_CALCULATION: 'features/core/product:coverage-calculation' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/core/technical:technical-requirements',
  'features/core/technical:typescript-support',
  'features/core/technical:bun-compatibility',
  'features/core/technical:glob-pattern-handling',
  'features/core/technical:markdown-parsing-accuracy',
  'features/core/dx:developer-experience',
  'features/core/dx:error-messages',
  'features/core/dx:api-design',
  'features/core/product:core-functionality',
  'features/core/product:structure-reading',
  'features/core/product:markdown-parsing',
  'features/core/product:test-scanning',
  'features/core/product:validation',
  'features/core/product:coverage-calculation',
];
