/**
 * Auto-generated Facet types for feature: core
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "core" feature
 */
export type FacetId =
  | 'product:core-functionality'
  | 'product:structure-reading'
  | 'product:markdown-parsing'
  | 'product:test-scanning'
  | 'product:validation'
  | 'product:coverage-calculation'
  | 'dx:developer-experience'
  | 'dx:error-messages'
  | 'dx:api-design'
  | 'technical:technical-requirements'
  | 'technical:typescript-support'
  | 'technical:bun-compatibility'
  | 'technical:glob-pattern-handling'
  | 'technical:markdown-parsing-accuracy';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Core Functionality */
  PRODUCT_CORE_FUNCTIONALITY: 'product:core-functionality' as const,
 /** Structure Reading */
  PRODUCT_STRUCTURE_READING: 'product:structure-reading' as const,
 /** Markdown Parsing */
  PRODUCT_MARKDOWN_PARSING: 'product:markdown-parsing' as const,
 /** Test Scanning */
  PRODUCT_TEST_SCANNING: 'product:test-scanning' as const,
 /** Validation */
  PRODUCT_VALIDATION: 'product:validation' as const,
 /** Coverage Calculation */
  PRODUCT_COVERAGE_CALCULATION: 'product:coverage-calculation' as const,
 /** Developer Experience */
  DX_DEVELOPER_EXPERIENCE: 'dx:developer-experience' as const,
 /** Error Messages */
  DX_ERROR_MESSAGES: 'dx:error-messages' as const,
 /** API Design */
  DX_API_DESIGN: 'dx:api-design' as const,
 /** Technical Requirements */
  TECHNICAL_TECHNICAL_REQUIREMENTS: 'technical:technical-requirements' as const,
 /** TypeScript Support */
  TECHNICAL_TYPESCRIPT_SUPPORT: 'technical:typescript-support' as const,
 /** Bun Compatibility */
  TECHNICAL_BUN_COMPATIBILITY: 'technical:bun-compatibility' as const,
 /** Glob Pattern Handling */
  TECHNICAL_GLOB_PATTERN_HANDLING: 'technical:glob-pattern-handling' as const,
 /** Markdown Parsing Accuracy */
  TECHNICAL_MARKDOWN_PARSING_ACCURACY: 'technical:markdown-parsing-accuracy' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'product:core-functionality',
  'product:structure-reading',
  'product:markdown-parsing',
  'product:test-scanning',
  'product:validation',
  'product:coverage-calculation',
  'dx:developer-experience',
  'dx:error-messages',
  'dx:api-design',
  'technical:technical-requirements',
  'technical:typescript-support',
  'technical:bun-compatibility',
  'technical:glob-pattern-handling',
  'technical:markdown-parsing-accuracy',
];
