/**
 * Auto-generated Global Facet types
 * Combines all features for single import point
 *
 * Generated by: bunx facet generate --global
 * DO NOT EDIT THIS FILE MANUALLY
 */

// Re-export all feature-specific types
export * as generate from '../features/cli/generate/.facet/facets';
export * as reporters from '../features/reporters/.facet/facets';
export * as integrations from '../features/integrations/.facet/facets';
export * as cli from '../features/cli/.facet/facets';
export * as core from '../features/core/.facet/facets';

/**
 * All valid facet IDs across ALL features
 */
export type FacetId =
  | 'features/cli/generate/product:generate-command'
  | 'features/cli/generate/product:config-based-discovery'
  | 'features/cli/generate/product:type-generation'
  | 'features/cli/generate/product:global-types'
  | 'features/reporters/dx:developer-experience'
  | 'features/reporters/dx:report-readability'
  | 'features/reporters/dx:report-accessibility'
  | 'features/reporters/product:report-generation'
  | 'features/reporters/product:json-reporter'
  | 'features/reporters/product:html-reporter'
  | 'features/reporters/product:markdown-reporter'
  | 'features/integrations/dx:developer-experience'
  | 'features/integrations/dx:integration-simplicity'
  | 'features/integrations/dx:annotation-syntax'
  | 'features/integrations/product:integrations'
  | 'features/integrations/product:playwright-annotation-helper'
  | 'features/integrations/product:playwright-reporter'
  | 'features/cli/dx:developer-experience'
  | 'features/cli/dx:cli-ergonomics'
  | 'features/cli/dx:configuration-discovery'
  | 'features/cli/product:cli-commands'
  | 'features/cli/product:generate-command'
  | 'features/cli/product:analyze-command'
  | 'features/cli/product:validate-command'
  | 'features/cli/product:watch-command'
  | 'features/core/technical:technical-requirements'
  | 'features/core/technical:typescript-support'
  | 'features/core/technical:bun-compatibility'
  | 'features/core/technical:glob-pattern-handling'
  | 'features/core/technical:markdown-parsing-accuracy'
  | 'features/core/dx:developer-experience'
  | 'features/core/dx:error-messages'
  | 'features/core/dx:api-design'
  | 'features/core/product:core-functionality'
  | 'features/core/product:structure-reading'
  | 'features/core/product:markdown-parsing'
  | 'features/core/product:test-scanning'
  | 'features/core/product:validation'
  | 'features/core/product:coverage-calculation';

/**
 * Combined Facet ID constants from all features
 */
export const Facets = {
 /** Generate Command */
  FEATURES_CLI_GENERATE_PRODUCT_GENERATE_COMMAND: 'features/cli/generate/product:generate-command' as const,
 /** Config-Based Discovery */
  FEATURES_CLI_GENERATE_PRODUCT_CONFIG_BASED_DISCOVERY: 'features/cli/generate/product:config-based-discovery' as const,
 /** Type Generation */
  FEATURES_CLI_GENERATE_PRODUCT_TYPE_GENERATION: 'features/cli/generate/product:type-generation' as const,
 /** Global Types */
  FEATURES_CLI_GENERATE_PRODUCT_GLOBAL_TYPES: 'features/cli/generate/product:global-types' as const,
 /** Developer Experience */
  FEATURES_REPORTERS_DX_DEVELOPER_EXPERIENCE: 'features/reporters/dx:developer-experience' as const,
 /** Report Readability */
  FEATURES_REPORTERS_DX_REPORT_READABILITY: 'features/reporters/dx:report-readability' as const,
 /** Report Accessibility */
  FEATURES_REPORTERS_DX_REPORT_ACCESSIBILITY: 'features/reporters/dx:report-accessibility' as const,
 /** Report Generation */
  FEATURES_REPORTERS_PRODUCT_REPORT_GENERATION: 'features/reporters/product:report-generation' as const,
 /** JSON Reporter */
  FEATURES_REPORTERS_PRODUCT_JSON_REPORTER: 'features/reporters/product:json-reporter' as const,
 /** HTML Reporter */
  FEATURES_REPORTERS_PRODUCT_HTML_REPORTER: 'features/reporters/product:html-reporter' as const,
 /** Markdown Reporter */
  FEATURES_REPORTERS_PRODUCT_MARKDOWN_REPORTER: 'features/reporters/product:markdown-reporter' as const,
 /** Developer Experience */
  FEATURES_INTEGRATIONS_DX_DEVELOPER_EXPERIENCE: 'features/integrations/dx:developer-experience' as const,
 /** Integration Simplicity */
  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY: 'features/integrations/dx:integration-simplicity' as const,
 /** Annotation Syntax */
  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX: 'features/integrations/dx:annotation-syntax' as const,
 /** Integrations */
  FEATURES_INTEGRATIONS_PRODUCT_INTEGRATIONS: 'features/integrations/product:integrations' as const,
 /** Playwright Annotation Helper */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER: 'features/integrations/product:playwright-annotation-helper' as const,
 /** Playwright Reporter */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER: 'features/integrations/product:playwright-reporter' as const,
 /** Developer Experience */
  FEATURES_CLI_DX_DEVELOPER_EXPERIENCE: 'features/cli/dx:developer-experience' as const,
 /** CLI Ergonomics */
  FEATURES_CLI_DX_CLI_ERGONOMICS: 'features/cli/dx:cli-ergonomics' as const,
 /** Configuration Discovery */
  FEATURES_CLI_DX_CONFIGURATION_DISCOVERY: 'features/cli/dx:configuration-discovery' as const,
 /** CLI Commands */
  FEATURES_CLI_PRODUCT_CLI_COMMANDS: 'features/cli/product:cli-commands' as const,
 /** Generate Command */
  FEATURES_CLI_PRODUCT_GENERATE_COMMAND: 'features/cli/product:generate-command' as const,
 /** Analyze Command */
  FEATURES_CLI_PRODUCT_ANALYZE_COMMAND: 'features/cli/product:analyze-command' as const,
 /** Validate Command */
  FEATURES_CLI_PRODUCT_VALIDATE_COMMAND: 'features/cli/product:validate-command' as const,
 /** Watch Command */
  FEATURES_CLI_PRODUCT_WATCH_COMMAND: 'features/cli/product:watch-command' as const,
 /** Technical Requirements */
  FEATURES_CORE_TECHNICAL_TECHNICAL_REQUIREMENTS: 'features/core/technical:technical-requirements' as const,
 /** TypeScript Support */
  FEATURES_CORE_TECHNICAL_TYPESCRIPT_SUPPORT: 'features/core/technical:typescript-support' as const,
 /** Bun Compatibility */
  FEATURES_CORE_TECHNICAL_BUN_COMPATIBILITY: 'features/core/technical:bun-compatibility' as const,
 /** Glob Pattern Handling */
  FEATURES_CORE_TECHNICAL_GLOB_PATTERN_HANDLING: 'features/core/technical:glob-pattern-handling' as const,
 /** Markdown Parsing Accuracy */
  FEATURES_CORE_TECHNICAL_MARKDOWN_PARSING_ACCURACY: 'features/core/technical:markdown-parsing-accuracy' as const,
 /** Developer Experience */
  FEATURES_CORE_DX_DEVELOPER_EXPERIENCE: 'features/core/dx:developer-experience' as const,
 /** Error Messages */
  FEATURES_CORE_DX_ERROR_MESSAGES: 'features/core/dx:error-messages' as const,
 /** API Design */
  FEATURES_CORE_DX_API_DESIGN: 'features/core/dx:api-design' as const,
 /** Core Functionality */
  FEATURES_CORE_PRODUCT_CORE_FUNCTIONALITY: 'features/core/product:core-functionality' as const,
 /** Structure Reading */
  FEATURES_CORE_PRODUCT_STRUCTURE_READING: 'features/core/product:structure-reading' as const,
 /** Markdown Parsing */
  FEATURES_CORE_PRODUCT_MARKDOWN_PARSING: 'features/core/product:markdown-parsing' as const,
 /** Test Scanning */
  FEATURES_CORE_PRODUCT_TEST_SCANNING: 'features/core/product:test-scanning' as const,
 /** Validation */
  FEATURES_CORE_PRODUCT_VALIDATION: 'features/core/product:validation' as const,
 /** Coverage Calculation */
  FEATURES_CORE_PRODUCT_COVERAGE_CALCULATION: 'features/core/product:coverage-calculation' as const,
} as const;

/**
 * Type-safe facet annotation helper (global version)
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * All facet IDs across all features
 */
export const allFacetIds: FacetId[] = [
  'features/cli/generate/product:generate-command',
  'features/cli/generate/product:config-based-discovery',
  'features/cli/generate/product:type-generation',
  'features/cli/generate/product:global-types',
  'features/reporters/dx:developer-experience',
  'features/reporters/dx:report-readability',
  'features/reporters/dx:report-accessibility',
  'features/reporters/product:report-generation',
  'features/reporters/product:json-reporter',
  'features/reporters/product:html-reporter',
  'features/reporters/product:markdown-reporter',
  'features/integrations/dx:developer-experience',
  'features/integrations/dx:integration-simplicity',
  'features/integrations/dx:annotation-syntax',
  'features/integrations/product:integrations',
  'features/integrations/product:playwright-annotation-helper',
  'features/integrations/product:playwright-reporter',
  'features/cli/dx:developer-experience',
  'features/cli/dx:cli-ergonomics',
  'features/cli/dx:configuration-discovery',
  'features/cli/product:cli-commands',
  'features/cli/product:generate-command',
  'features/cli/product:analyze-command',
  'features/cli/product:validate-command',
  'features/cli/product:watch-command',
  'features/core/technical:technical-requirements',
  'features/core/technical:typescript-support',
  'features/core/technical:bun-compatibility',
  'features/core/technical:glob-pattern-handling',
  'features/core/technical:markdown-parsing-accuracy',
  'features/core/dx:developer-experience',
  'features/core/dx:error-messages',
  'features/core/dx:api-design',
  'features/core/product:core-functionality',
  'features/core/product:structure-reading',
  'features/core/product:markdown-parsing',
  'features/core/product:test-scanning',
  'features/core/product:validation',
  'features/core/product:coverage-calculation',
];
