/**
 * Auto-generated Facet types for feature: reporters
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "reporters" feature
 */
export type FacetId =
  | 'product:report-generation'
  | 'product:json-reporter'
  | 'product:html-reporter'
  | 'product:markdown-reporter'
  | 'dx:developer-experience'
  | 'dx:report-readability'
  | 'dx:report-accessibility';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Report Generation */
  PRODUCT_REPORT_GENERATION: 'product:report-generation' as const,
 /** JSON Reporter */
  PRODUCT_JSON_REPORTER: 'product:json-reporter' as const,
 /** HTML Reporter */
  PRODUCT_HTML_REPORTER: 'product:html-reporter' as const,
 /** Markdown Reporter */
  PRODUCT_MARKDOWN_REPORTER: 'product:markdown-reporter' as const,
 /** Developer Experience */
  DX_DEVELOPER_EXPERIENCE: 'dx:developer-experience' as const,
 /** Report Readability */
  DX_REPORT_READABILITY: 'dx:report-readability' as const,
 /** Report Accessibility */
  DX_REPORT_ACCESSIBILITY: 'dx:report-accessibility' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'product:report-generation',
  'product:json-reporter',
  'product:html-reporter',
  'product:markdown-reporter',
  'dx:developer-experience',
  'dx:report-readability',
  'dx:report-accessibility',
];
