/**
 * Auto-generated Facet types for feature: integrations
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "integrations" feature
 */
export type FacetId =
  | 'features/integrations/dx:developer-experience'
  | 'features/integrations/dx:integration-simplicity'
  | 'features/integrations/dx:integration-simplicity/minimal-config'
  | 'features/integrations/dx:integration-simplicity/clear-imports'
  | 'features/integrations/dx:integration-simplicity/playwright-compat'
  | 'features/integrations/dx:integration-simplicity/no-modifications'
  | 'features/integrations/dx:annotation-syntax'
  | 'features/integrations/dx:annotation-syntax/multi-id-annotation'
  | 'features/integrations/dx:annotation-syntax/natural-syntax'
  | 'features/integrations/dx:annotation-syntax/separation'
  | 'features/integrations/dx:annotation-syntax/annotation-types'
  | 'features/integrations/product:integrations'
  | 'features/integrations/product:type-safe-facet-function'
  | 'features/integrations/product:type-safe-facet-function/variadic-args'
  | 'features/integrations/product:type-safe-facet-function/typescript-autocomplete'
  | 'features/integrations/product:type-safe-facet-function/framework-agnostic'
  | 'features/integrations/product:type-safe-facet-function/constant-refs'
  | 'features/integrations/product:type-safe-facet-function/multiple-ids'
  | 'features/integrations/product:type-safe-facet-function/metadata-return'
  | 'features/integrations/product:type-safe-facet-function/compile-time-check'
  | 'features/integrations/product:playwright-annotation-helper'
  | 'features/integrations/product:playwright-annotation-helper/pw-facet-function'
  | 'features/integrations/product:playwright-annotation-helper/pw-annotation-object'
  | 'features/integrations/product:playwright-annotation-helper/pw-multiple-ids'
  | 'features/integrations/product:playwright-annotation-helper/pw-test-syntax'
  | 'features/integrations/product:playwright-reporter'
  | 'features/integrations/product:playwright-reporter/pw-reporter-interface'
  | 'features/integrations/product:playwright-reporter/pw-extract-annotations'
  | 'features/integrations/product:playwright-reporter/pw-passed-only'
  | 'features/integrations/product:playwright-reporter/pw-merge-data'
  | 'features/integrations/product:playwright-reporter/pw-report-formats'
  | 'features/integrations/product:playwright-reporter/pw-console-summary'
  | 'features/integrations/product:playwright-reporter/pw-config-options'
  | 'features/integrations/product:playwright-reporter/pw-other-reporters';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Developer Experience */
  FEATURES_INTEGRATIONS_DX_DEVELOPER_EXPERIENCE: 'features/integrations/dx:developer-experience' as const,
 /** Integration Simplicity */
  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY: 'features/integrations/dx:integration-simplicity' as const,

  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY__MINIMAL_CONFIG: 'features/integrations/dx:integration-simplicity/minimal-config' as const,

  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY__CLEAR_IMPORTS: 'features/integrations/dx:integration-simplicity/clear-imports' as const,

  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY__PLAYWRIGHT_COMPAT: 'features/integrations/dx:integration-simplicity/playwright-compat' as const,

  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY__NO_MODIFICATIONS: 'features/integrations/dx:integration-simplicity/no-modifications' as const,
 /** Annotation Syntax */
  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX: 'features/integrations/dx:annotation-syntax' as const,

  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX__MULTI_ID_ANNOTATION: 'features/integrations/dx:annotation-syntax/multi-id-annotation' as const,

  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX__NATURAL_SYNTAX: 'features/integrations/dx:annotation-syntax/natural-syntax' as const,

  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX__SEPARATION: 'features/integrations/dx:annotation-syntax/separation' as const,

  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX__ANNOTATION_TYPES: 'features/integrations/dx:annotation-syntax/annotation-types' as const,
 /** Integrations */
  FEATURES_INTEGRATIONS_PRODUCT_INTEGRATIONS: 'features/integrations/product:integrations' as const,
 /** Type-Safe Facet Function */
  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION: 'features/integrations/product:type-safe-facet-function' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__VARIADIC_ARGS: 'features/integrations/product:type-safe-facet-function/variadic-args' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__TYPESCRIPT_AUTOCOMPLETE: 'features/integrations/product:type-safe-facet-function/typescript-autocomplete' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__FRAMEWORK_AGNOSTIC: 'features/integrations/product:type-safe-facet-function/framework-agnostic' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__CONSTANT_REFS: 'features/integrations/product:type-safe-facet-function/constant-refs' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__MULTIPLE_IDS: 'features/integrations/product:type-safe-facet-function/multiple-ids' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__METADATA_RETURN: 'features/integrations/product:type-safe-facet-function/metadata-return' as const,

  FEATURES_INTEGRATIONS_PRODUCT_TYPE_SAFE_FACET_FUNCTION__COMPILE_TIME_CHECK: 'features/integrations/product:type-safe-facet-function/compile-time-check' as const,
 /** Playwright Annotation Helper */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER: 'features/integrations/product:playwright-annotation-helper' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER__PW_FACET_FUNCTION: 'features/integrations/product:playwright-annotation-helper/pw-facet-function' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER__PW_ANNOTATION_OBJECT: 'features/integrations/product:playwright-annotation-helper/pw-annotation-object' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER__PW_MULTIPLE_IDS: 'features/integrations/product:playwright-annotation-helper/pw-multiple-ids' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER__PW_TEST_SYNTAX: 'features/integrations/product:playwright-annotation-helper/pw-test-syntax' as const,
 /** Playwright Reporter */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER: 'features/integrations/product:playwright-reporter' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_REPORTER_INTERFACE: 'features/integrations/product:playwright-reporter/pw-reporter-interface' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_EXTRACT_ANNOTATIONS: 'features/integrations/product:playwright-reporter/pw-extract-annotations' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_PASSED_ONLY: 'features/integrations/product:playwright-reporter/pw-passed-only' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_MERGE_DATA: 'features/integrations/product:playwright-reporter/pw-merge-data' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_REPORT_FORMATS: 'features/integrations/product:playwright-reporter/pw-report-formats' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_CONSOLE_SUMMARY: 'features/integrations/product:playwright-reporter/pw-console-summary' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_CONFIG_OPTIONS: 'features/integrations/product:playwright-reporter/pw-config-options' as const,

  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER__PW_OTHER_REPORTERS: 'features/integrations/product:playwright-reporter/pw-other-reporters' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/integrations/dx:developer-experience',
  'features/integrations/dx:integration-simplicity',
  'features/integrations/dx:integration-simplicity/minimal-config',
  'features/integrations/dx:integration-simplicity/clear-imports',
  'features/integrations/dx:integration-simplicity/playwright-compat',
  'features/integrations/dx:integration-simplicity/no-modifications',
  'features/integrations/dx:annotation-syntax',
  'features/integrations/dx:annotation-syntax/multi-id-annotation',
  'features/integrations/dx:annotation-syntax/natural-syntax',
  'features/integrations/dx:annotation-syntax/separation',
  'features/integrations/dx:annotation-syntax/annotation-types',
  'features/integrations/product:integrations',
  'features/integrations/product:type-safe-facet-function',
  'features/integrations/product:type-safe-facet-function/variadic-args',
  'features/integrations/product:type-safe-facet-function/typescript-autocomplete',
  'features/integrations/product:type-safe-facet-function/framework-agnostic',
  'features/integrations/product:type-safe-facet-function/constant-refs',
  'features/integrations/product:type-safe-facet-function/multiple-ids',
  'features/integrations/product:type-safe-facet-function/metadata-return',
  'features/integrations/product:type-safe-facet-function/compile-time-check',
  'features/integrations/product:playwright-annotation-helper',
  'features/integrations/product:playwright-annotation-helper/pw-facet-function',
  'features/integrations/product:playwright-annotation-helper/pw-annotation-object',
  'features/integrations/product:playwright-annotation-helper/pw-multiple-ids',
  'features/integrations/product:playwright-annotation-helper/pw-test-syntax',
  'features/integrations/product:playwright-reporter',
  'features/integrations/product:playwright-reporter/pw-reporter-interface',
  'features/integrations/product:playwright-reporter/pw-extract-annotations',
  'features/integrations/product:playwright-reporter/pw-passed-only',
  'features/integrations/product:playwright-reporter/pw-merge-data',
  'features/integrations/product:playwright-reporter/pw-report-formats',
  'features/integrations/product:playwright-reporter/pw-console-summary',
  'features/integrations/product:playwright-reporter/pw-config-options',
  'features/integrations/product:playwright-reporter/pw-other-reporters',
];
