/**
 * Auto-generated Facet types for feature: integrations
 * Generated by: bunx facet generate
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * All valid facet IDs for the "integrations" feature
 */
export type FacetId =
  | 'features/integrations/dx:developer-experience'
  | 'features/integrations/dx:integration-simplicity'
  | 'features/integrations/dx:annotation-syntax'
  | 'features/integrations/product:integrations'
  | 'features/integrations/product:playwright-annotation-helper'
  | 'features/integrations/product:playwright-reporter';

/**
 * Facet ID constants for autocomplete and type-safe references
 */
export const Facets = {
 /** Developer Experience */
  FEATURES_INTEGRATIONS_DX_DEVELOPER_EXPERIENCE: 'features/integrations/dx:developer-experience' as const,
 /** Integration Simplicity */
  FEATURES_INTEGRATIONS_DX_INTEGRATION_SIMPLICITY: 'features/integrations/dx:integration-simplicity' as const,
 /** Annotation Syntax */
  FEATURES_INTEGRATIONS_DX_ANNOTATION_SYNTAX: 'features/integrations/dx:annotation-syntax' as const,
 /** Integrations */
  FEATURES_INTEGRATIONS_PRODUCT_INTEGRATIONS: 'features/integrations/product:integrations' as const,
 /** Playwright Annotation Helper */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_ANNOTATION_HELPER: 'features/integrations/product:playwright-annotation-helper' as const,
 /** Playwright Reporter */
  FEATURES_INTEGRATIONS_PRODUCT_PLAYWRIGHT_REPORTER: 'features/integrations/product:playwright-reporter' as const,
} as const;

/**
 * Type-safe facet annotation helper
 * Works with any testing framework
 *
 * @example
 * // Use with constants (recommended - full autocomplete)
 * // @facet ${Facets.BUSINESS_GUEST_PURCHASE_FLOW}
 * test('my test', () => { ... });
 *
 * @example
 * // Use with facet() for runtime metadata
 * const metadata = facet(Facets.BUSINESS_GUEST_PURCHASE_FLOW, Facets.COMPLIANCE_PCI_DSS);
 */
export function facet<T extends FacetId>(...facetIds: T[]): { facets: T[]; toString: () => string } {
  return {
    facets: facetIds,
    toString: () => facetIds.join(', '),
  };
}

/**
 * Get all facet IDs as an array
 */
export const allFacetIds: FacetId[] = [
  'features/integrations/dx:developer-experience',
  'features/integrations/dx:integration-simplicity',
  'features/integrations/dx:annotation-syntax',
  'features/integrations/product:integrations',
  'features/integrations/product:playwright-annotation-helper',
  'features/integrations/product:playwright-reporter',
];
